# 2.6 Subspaces

The visualizations in the textbook's Section 2.6 are very valuable. You should spend time with all of the interactive modules and take time with the definitions and theorems.

The key task in the section is finding the solution set of the *null space*.

Null Space
: The set of all solution vectors to the homogenenous equations.



## Finding the null space

### Example 1. Find the null space of the matrix $A$.

$$A = \left[\begin{array}{rrr}4&-18&-21\\-4&30&33\\0&1&1\\\end{array}\right]$$

In [23]:
A = [  4   -18   -21 ;
      -4    30    33 ;
       0     1     1 ]


A =

     4   -18   -21
    -4    30    33
     0     1     1




To dtermine the null space, we need to augment the matrix $A$ with the zero vector.

In [24]:
[A,zeros(3,1)]


ans =

     4   -18   -21     0
    -4    30    33     0
     0     1     1     0




In [25]:
rref([A,zeros(3,1)])


ans =

    1.0000         0   -0.7500         0
         0    1.0000    1.0000         0
         0         0         0         0




Now we write the solution set in vector form. The first step is to write all basic variables in terms of the free variables.

$$\begin{align*} x_1 &= \frac{3}{4}x_3 \\ x_2 &= -x_3 \end{align*}$$

So the solution set is of the form:

$$ \vec x = \left[\begin{array}{r}\frac{3}{4}\\-1\\1\\\end{array}\right]$$

To verify the solution is correct, we can create the vector $\vec x$ and evaluate what happens when we take scalar multiples of it and multiply by $B$.

In [26]:
x = [ 3/4 ; -1 ; 1]


x =

    0.7500
   -1.0000
    1.0000




In [27]:
A * (5 * x) 


ans =

     0
     0
     0




This isn't proof that *any* scalar multiple of $\vec x$ is a solution, but we can check several randomly chosen scalar multiples.

for i = 1:10
    k = randi([-50 100],1,1);
    A * k * x
end

### Example 2. Find the null space of the matrix $B$.

$$ B = \left[\begin{array}{rrr}-1&4&1\\-3&12&7\\0&1&-2\end{array}\right] $$

In [28]:
B = [ -1 4 1 ; -3 12 7 ; 0 1 -2 ]
rref([B, zeros(3,1)])


B =

    -1     4     1
    -3    12     7
     0     1    -2


ans =

     1     0     0     0
     0     1     0     0
     0     0     1     0




Clearly, the only solution to the homogeneous equations is the zero vector which makes sense. Because there are three pivots, there are no free variables. We use the notation below for the null space of a matrix.

$$\text{Null}(B)=\vec 0$$

## Example 3

Find the null space for matrix $C$.

$$C = \left[\begin{array}{rrrr}0&0&1&-2\\-12&43&27&9\\-2&7&4&1\\\end{array}\right]$$

Again, we need the matrix C.

In [31]:
C = [  0     0     1    -2 ;
     -12    43    27     9 ;
      -2     7     4     1 ]
[C , zeros(3,1)]
rref([C , zeros(3,1)])


C =

     0     0     1    -2
   -12    43    27     9
    -2     7     4     1


ans =

     0     0     1    -2     0
   -12    43    27     9     0
    -2     7     4     1     0


ans =

     1     0     0    27     0
     0     1     0     9     0
     0     0     1    -2     0




Clearly, $x_1 = -27 x_4$, $x_2 = -9 x_4$ and $x_3 = -2 x_4$ which is closely related to the fourth column of $C$.